{
    "body": "While installing lmod, `luaposix` fails to download.\r\n\r\n```\r\ncurl: (22) The requested URL returned error: 404 Not Found\r\n==> Fetching https://github.com/luaposix/luaposix/archive/33.4.0.tar.gz\r\n==> Fetching from https://github.com/luaposix/luaposix/archive/33.4.0.tar.gz failed.\r\n==> Error: FetchError: All fetchers failed for lua-luaposix-33.4.0-oiq5d2je66cshng6oiihy3cb3pvqausl\r\n```\r\n\r\nThe tarball exists here:  https://github.com/luaposix/luaposix/archive/release-v33.4.0.tar.gz\r\n\r\nand here's the relevant bit of the package.py\r\n\r\n```\r\n    homepage = \"https://github.com/luaposix/luaposix/\"\r\n    url      = \"https://github.com/luaposix/luaposix/archive/release-v33.4.0.tar.gz\"\r\n\r\n    version('33.4.0', 'b36ff049095f28752caeb0b46144516c')\r\n```\r\n\r\nThe package itself hasn't changed.  I think I remember fetching code being reworked recently.  Does this ring any bells?\r\n\r\ng.\r\n\r\n\r\n",
    "user": "hartzell",
    "url": "https://api.github.com/repos/spack/spack/issues/2676",
    "updated_at": "2016-12-25 04:52:33",
    "created_at": "2016-12-25 00:38:07",
    "closed_at": "2016-12-25 04:52:27",
    "state": "closed",
    "title": "luaposix fails to download",
    "number": 2676,
    "milestone": null,
    "labels": [
        "bug",
        "duplicate"
    ],
    "id": 197482575,
    "html_url": "https://github.com/spack/spack/issues/2676",
    "assignees": [],
    "comments": 2
}