{
    "body": "When trying to install a package (`py-yt`) that depends on `py-ipython`, I encounter an error:\r\n```\r\n==> Installing py-ipython\r\n==> Using cached archive: /Users/eschnett/src/spack/var/spack/cache/py-ipython/py-ipython-6.0.0.tar.gz\r\n==> Staging archive: /Users/eschnett/src/spack/var/spack/stage/py-ipython-6.0.0-6fpapngzec2htcor6wusiiszsedzdfht/ipython-6.0.0.tar.gz\r\n==> Created stage in /Users/eschnett/src/spack/var/spack/stage/py-ipython-6.0.0-6fpapngzec2htcor6wusiiszsedzdfht\r\n==> Ran patch() for py-ipython\r\n==> Building py-ipython [PythonPackage]\r\n==> Executing phase : 'build'\r\n==> '/Users/eschnett/src/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/python-2.7.13-lbt26chwl7kqnobyhddt2kt4cutpwxrw/bin/python2.7' 'setup.py' '--no-user-cfg' 'build'\r\n\r\n==> Error: ProcessError: Command exited with status 1:\r\n    '/Users/eschnett/src/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/python-2.7.13-lbt26chwl7kqnobyhddt2kt4cutpwxrw/bin/python2.7' 'setup.py' '--no-user-cfg' 'build'\r\n/Users/eschnett/src/spack/lib/spack/spack/build_systems/python.py:129, in python:\r\n     128      def python(self, *args, **kwargs):\r\n  >> 129          inspect.getmodule(self).python(*args, **kwargs)\r\n\r\nSee build log for details:\r\n  /private/var/folders/gl/zvl8d6415vsbkd50nnll95k40000gs/T/eschnett/spack-stage/spack-stage-o2dAFi/ipython-6.0.0/spack-build.out\r\n```\r\n\r\n`spack-build.out` contains only this:\r\n```\r\n==> '/Users/eschnett/src/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/python-2.7.13-lbt26chwl7kqnobyhddt2kt4cutpwxrw/bin/python2.7' 'setup.py' '--no-user-cfg' 'build'\r\n\r\n```\r\n\r\nNo further output exists to debug this. It seems that the call to `setup.py` fails, but I can't see any log output or error message. How do I debug this?",
    "user": "eschnett",
    "url": "https://api.github.com/repos/spack/spack/issues/4195",
    "updated_at": "2017-11-23 12:29:27",
    "created_at": "2017-05-10 15:07:41",
    "closed_at": "2017-11-23 12:29:20",
    "state": "closed",
    "title": "Cannot install py-ipython -- no reasonable error message -- how to debug?",
    "number": 4195,
    "milestone": null,
    "labels": [
        "build-error",
        "unreproducible"
    ],
    "id": 227712547,
    "html_url": "https://github.com/spack/spack/issues/4195",
    "assignees": [],
    "comments": 2
}