{
    "body": "Fixes a bug introduced in #28195. The new versions that were added used the checksums from the PyPI tarballs, not the GitHub tarballs. We might as well start using PyPI tarballs for this package instead.\r\n\r\n@mdorier ",
    "user": "adamjstewart",
    "url": "https://api.github.com/repos/spack/spack/issues/28329",
    "updated_at": "2022-01-12 14:54:49",
    "created_at": "2022-01-09 03:27:45",
    "closed_at": "2022-01-12 09:53:13",
    "state": "closed",
    "title": "py-async-timeout: fix checksum issue",
    "number": 28329,
    "milestone": null,
    "labels": [
        "new-version",
        "python",
        "update-package"
    ],
    "id": 1097094958,
    "html_url": "https://github.com/spack/spack/pull/28329",
    "assignees": [],
    "comments": 0
}