{
    "body": "This value points to the full path of spack.yaml:\r\nhttps://github.com/spack/spack/blob/76ad001c563bfdd1821b590110cbe83e1b177d03/lib/spack/spack/cmd/config.py#L255\r\nI think it should get the os.path.dirname(scope.path), since \r\nhttps://github.com/spack/spack/blob/76ad001c563bfdd1821b590110cbe83e1b177d03/lib/spack/spack/cmd/config.py#L240\r\ngives dir_ok=False when passed a file, not a directory, then I get a permissions error from:\r\nhttps://github.com/spack/spack/blob/76ad001c563bfdd1821b590110cbe83e1b177d03/lib/spack/spack/cmd/config.py#L266\r\nwhen I do `spack config update config` which was requested by `spack` when I tried a `spack install` of Trilinos.",
    "user": "skennon10",
    "url": "https://api.github.com/repos/spack/spack/issues/26169",
    "updated_at": "2021-10-04 11:41:35",
    "created_at": "2021-09-22 17:00:42",
    "closed_at": "None",
    "state": "open",
    "title": "Path to config issue",
    "number": 26169,
    "milestone": null,
    "labels": [
        "bug",
        "triage"
    ],
    "id": 1004521531,
    "html_url": "https://github.com/spack/spack/issues/26169",
    "assignees": [],
    "comments": 0
}