{
    "body": "Since we moved from `travis-ci.org` to `travis-ci.com` unit tests are failing. It seems the issue is that stdout and stderr are not captured by `pytest` and thus unit tests using `capfd` are failing.\r\n\r\n### Steps to reproduce the issue\r\n\r\nRun unit tests under `travis-ci.com`, see e.g. [this](https://travis-ci.com/github/spack/spack/jobs/330679066)\r\n\r\n### Error Message\r\n\r\nNot relevant\r\n\r\n### Information on your system\r\n\r\nNot relevant\r\n\r\n### Additional information\r\n\r\nThe same issue is present on Github Actions, see #14220\r\n\r\n- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform\r\n- [x] I have searched the issues of this repo and believe this is not a duplicate\r\n- [ ] I have run the failing commands in debug mode and reported the output\r\n",
    "user": "alalazo",
    "url": "https://api.github.com/repos/spack/spack/issues/16532",
    "updated_at": "2020-05-09 20:34:35",
    "created_at": "2020-05-08 19:21:18",
    "closed_at": "2020-05-09 20:34:35",
    "state": "closed",
    "title": "Unit tests are failing on travis-ci.com",
    "number": 16532,
    "milestone": null,
    "labels": [
        "bug",
        "broken-develop",
        "impact-high",
        "travis"
    ],
    "id": 614935090,
    "html_url": "https://github.com/spack/spack/issues/16532",
    "assignees": [],
    "comments": 0
}