{
    "body": "`spack gpg trust` is now returning non-zero exit status on RHEL7 even when the *spack* command itself is being properly used.\r\n\r\nSpack info:\r\n* `spack@develop` (8919226dc6110403ac0f0ef6fa01abe59d493f89)\r\n* `Mon Dec 28 17:56:15 2020 +0100`):\r\n\r\nI'm using the following Docker images, which are based on the official RHEL 7 UBI image (`registry.access.redhat.com/ubi7/ubi:7.6-239`)\r\n* `ecpe4s/rhel7-runner-x86_64:2020-12-01`\r\n* `ecpe4s/rhel7-runner-ppc64le:2020-12-01`\r\n\r\nGPG version info:\r\n```\r\n$> gpg --version\r\ngpg (GnuPG) 2.0.22\r\nlibgcrypt 1.5.3\r\n...\r\n```\r\n\r\nHere's the problem as it presents itself:\r\n```\r\n$> spack --version\r\n0.16.0-389-8919226\r\n```\r\n\r\n```\r\n$> spack gpg trust e4s.pub\r\ngpgconf: invalid option \"--create-socketdir\"\r\n==> Error: None: No such file or directory: 'None'\r\nCommand: 'None' '--create-socketdir'\r\n```\r\n\r\n```\r\n$> spack -d gpg trust e4s.pub\r\n==> [2020-12-28-17:57:13.255469] Imported gpg from built-in commands\r\n==> [2020-12-28-17:57:13.257931] Imported gpg from built-in commands\r\n==> [2020-12-28-17:57:13.258679] '/usr/bin/gpgconf' '--version'\r\n==> [2020-12-28-17:57:13.260456] '/usr/bin/gpgconf' '--dry-run' '--create-socketdir'\r\ngpgconf: invalid option \"--create-socketdir\"\r\n==> [2020-12-28-17:57:13.262194] '/usr/bin/gpg2' '--version'\r\n==> [2020-12-28-17:57:13.264410] 'None' '--create-socketdir'\r\n==> [2020-12-28-17:57:13.265610] ProcessError: None: No such file or directory: 'None'\r\n    Command: 'None' '--create-socketdir'\r\n==> [2020-12-28-17:57:13.265703] Error: None: No such file or directory: 'None'\r\nCommand: 'None' '--create-socketdir'\r\nTraceback (most recent call last):\r\n  File \"/opt/spack/lib/spack/spack/util/executable.py\", line 170, in __call__\r\n    env=env)\r\n  File \"/usr/local/lib/python3.7/subprocess.py\", line 775, in __init__\r\n    restore_signals, start_new_session)\r\n  File \"/usr/local/lib/python3.7/subprocess.py\", line 1522, in _execute_child\r\n    raise child_exception_type(errno_num, err_msg, err_filename)\r\nFileNotFoundError: [Errno 2] No such file or directory: 'None': 'None'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/opt/spack/lib/spack/spack/main.py\", line 762, in main\r\n    return _invoke_command(command, parser, args, unknown)\r\n  File \"/opt/spack/lib/spack/spack/main.py\", line 490, in _invoke_command\r\n    return_val = command(parser, args)\r\n  File \"/opt/spack/lib/spack/spack/cmd/gpg.py\", line 201, in gpg\r\n    args.func(args)\r\n  File \"/opt/spack/lib/spack/spack/cmd/gpg.py\", line 159, in gpg_trust\r\n    spack.util.gpg.trust(args.keyfile)\r\n  File \"/opt/spack/lib/spack/spack/util/gpg.py\", line 410, in trust\r\n    return get_global_gpg_instance().trust(*args, **kwargs)\r\n  File \"/opt/spack/lib/spack/spack/util/gpg.py\", line 345, in trust\r\n    self('--import', keyfile)\r\n  File \"/opt/spack/lib/spack/spack/util/gpg.py\", line 307, in __call__\r\n    if self.prep:\r\n  File \"/opt/spack/lib/spack/llnl/util/lang.py\", line 197, in _memoized_function\r\n    func.cache[args] = func(*args)\r\n  File \"/opt/spack/lib/spack/spack/util/gpg.py\", line 290, in prep\r\n    self.gpgconf_exe('--create-socketdir')\r\n  File \"/opt/spack/lib/spack/spack/util/executable.py\", line 204, in __call__\r\n    '%s: %s' % (self.exe[0], e.strerror), 'Command: ' + cmd_line)\r\nspack.util.executable.ProcessError: None: No such file or directory: 'None'\r\n    Command: 'None' '--create-socketdir'\r\n```\r\n\r\nThe commit that introduced the issue is:\r\n* 857749a9ba3619f8190cc8b817d66125cf846c94\r\n* `Tue Dec 22 21:39:10 2020 -0800`\r\n\r\nI'm not seeing this problem on RHEL8, Ubuntu 18.04 or Ubuntu 20.04.\r\n\r\n@opadron @shahzebsiddiqui @scottwittenburg @trws ",
    "user": "eugeneswalker",
    "url": "https://api.github.com/repos/spack/spack/issues/20585",
    "updated_at": "2021-01-06 20:29:01",
    "created_at": "2020-12-28 18:00:44",
    "closed_at": "2021-01-06 20:29:01",
    "state": "closed",
    "title": "spack gpg trust fails on RHEL7: \"--create-socketdir\": invalid option",
    "number": 20585,
    "milestone": null,
    "labels": [
        "bug",
        "ecp",
        "triage",
        "e4s",
        "pipelines"
    ],
    "id": 775519315,
    "html_url": "https://github.com/spack/spack/issues/20585",
    "assignees": [],
    "comments": 8
}