{
    "body": "I am having a hard time building glib on Cray systems. Spack builds it just fine on RHEL and Mac OS. It seems to be hitting a snag in `/usr/bin/dtrace`. I wonder if this is just a faulty dtrace that is provided with SuSE? Has anyone else run into this?\n\nRelevant errors:\n\n```\nmake[2]: Entering directory `/tmp/frenchrd/spack-stage/spack-stage-8szQIo/glib-2.42.1/glib'\n  GEN      glibconfig-stamp\n  GEN      glib_probes.lo\nTraceback (most recent call last):\n  File \"/usr/bin/dtrace\", line 281, in <module>\n    main()\n  File \"/usr/bin/dtrace\", line 268, in main\n    filename + \".o\"], shell=False)\n  File \"/usr/lib64/python2.6/subprocess.py\", line 470, in call\n    return Popen(*popenargs, **kwargs).wait()\n  File \"/usr/lib64/python2.6/subprocess.py\", line 623, in __init__\n    errread, errwrite)\n  File \"/usr/lib64/python2.6/subprocess.py\", line 1141, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory\nmake[2]: *** [glib_probes.lo] Error 1\n```\n",
    "user": "robertdfrench",
    "url": "https://api.github.com/repos/spack/spack/issues/1134",
    "updated_at": "2016-06-28 22:02:42",
    "created_at": "2016-06-28 16:28:29",
    "closed_at": "2016-06-28 22:02:42",
    "state": "closed",
    "title": "glib 2.42.1 not building correctly on CrayXC-SuSE11",
    "number": 1134,
    "milestone": null,
    "labels": [],
    "id": 162729312,
    "html_url": "https://github.com/spack/spack/issues/1134",
    "assignees": [],
    "comments": 1
}