{
    "body": "Migrated out of https://github.com/spack/spack/issues/2495#issuecomment-419636297\r\n\r\nJust moving it out not to clutter it further.\r\n\r\nI currently get an infinite recursion on a fresh copy of spack `develop` (ccbff6e0cdc1e4e045656a784e28225f416a8ed4) and removed `$HOME/.spack` directory on `. share/spack/setup_env.sh` in Debian 9.5 \"stretch\".\r\n\r\n### Steps to reproduce the issue\r\n\r\nSee [docker image](https://github.com/spack/spack/issues/9206#issuecomment-420201058) below. Basically, make sure to have a recent version of `ruamel.yaml` on your system.\r\n\r\n### Error Message\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/home/axel/src/spack/bin/spack\", line 54, in <module>\r\n    sys.exit(spack.main.main())\r\n  File \"/home/axel/src/spack/lib/spack/spack/main.py\", line 600, in main\r\n    print_setup_info(*args.print_shell_vars.split(','))\r\n  File \"/home/axel/src/spack/lib/spack/spack/main.py\", line 565, in print_setup_info\r\n    module_roots = spack.config.get('config:module_roots')\r\n  File \"/home/axel/src/spack/lib/spack/spack/config.py\", line 573, in get\r\n    return config.get(path, default, scope)\r\n  File \"/home/axel/src/spack/lib/spack/llnl/util/lang.py\", line 556, in __getattr__\r\n    return getattr(self.instance, name)\r\n  File \"/home/axel/src/spack/lib/spack/llnl/util/lang.py\", line 556, in __getattr__\r\n    return getattr(self.instance, name)\r\n  File \"/home/axel/src/spack/lib/spack/llnl/util/lang.py\", line 556, in __getattr__\r\n    return getattr(self.instance, name)\r\n  [Previous line repeated 318 more times]\r\n  File \"/home/axel/src/spack/lib/spack/llnl/util/lang.py\", line 552, in instance\r\n    self._instance = self.factory()\r\n  File \"/home/axel/src/spack/lib/spack/spack/config.py\", line 547, in _config\r\n    defaults = InternalConfigScope('_builtin', config_defaults)\r\n  File \"/home/axel/src/spack/lib/spack/spack/config.py\", line 238, in __init__\r\n    _validate_section({section: dsec}, section_schemas[section])\r\n  File \"/home/axel/src/spack/lib/spack/spack/config.py\", line 611, in _validate_section\r\n    _validate_section.validator(schema).validate(data)\r\n  File \"/home/axel/src/spack/lib/spack/external/jsonschema/validators.py\", line 67, in __init__\r\n    resolver = RefResolver.from_schema(schema)\r\n  File \"/home/axel/src/spack/lib/spack/external/jsonschema/validators.py\", line 260, in from_schema\r\n    return cls(schema.get(u\"id\", u\"\"), schema, *args, **kwargs)\r\n  File \"/home/axel/src/spack/lib/spack/external/jsonschema/validators.py\", line 245, in __init__\r\n    for id, validator in iteritems(meta_schemas)\r\n  File \"/home/axel/src/spack/lib/spack/external/jsonschema/_utils.py\", line 20, in __init__\r\n    self.store.update(*args, **kwargs)\r\n  File \"/home/axel/src/spack/lib/spack/external/jsonschema/validators.py\", line 244, in <genexpr>\r\n    (id, validator.META_SCHEMA)\r\n  File \"/home/axel/miniconda3/lib/python3.6/_collections_abc.py\", line 744, in __iter__\r\n    yield (key, self._mapping[key])\r\n  File \"/home/axel/src/spack/lib/spack/external/jsonschema/_utils.py\", line 23, in __getitem__\r\n    return self.store[self.normalize(uri)]\r\n  File \"/home/axel/src/spack/lib/spack/external/jsonschema/_utils.py\", line 16, in normalize\r\n    return urlsplit(uri).geturl()\r\n  File \"/home/axel/src/spack/lib/spack/external/jsonschema/compat.py\", line 37, in urlsplit\r\n    scheme, netloc, path, query, fragment = _urlsplit(url)\r\n  File \"/home/axel/miniconda3/lib/python3.6/urllib/parse.py\", line 398, in urlsplit\r\n    url, scheme, _coerce_result = _coerce_args(url, scheme)\r\nRecursionError: maximum recursion depth exceeded\r\n```\r\n\r\n\r\n### Information on your system\r\n\r\nPython 3.6.4 from Anaconda\r\nruamel.yaml 0.15.37\r\nDebian 9.5",
    "user": "ax3l",
    "url": "https://api.github.com/repos/spack/spack/issues/9206",
    "updated_at": "2018-11-07 00:06:19",
    "created_at": "2018-09-11 08:00:44",
    "closed_at": "2018-11-07 00:06:19",
    "state": "closed",
    "title": "Debian ruamel.yaml 0.15: Infinite Recoursion On Setup",
    "number": 9206,
    "milestone": null,
    "labels": [
        "bug",
        "linux",
        "broken-develop"
    ],
    "id": 358931272,
    "html_url": "https://github.com/spack/spack/issues/9206",
    "assignees": [],
    "comments": 24
}