{
    "body": "mac-127459:spack gartung$ spack graph --concretize gallery@dev%gcc@4.9.3 \n...\n\n| | | |/| |_|_|_|_|_|/Traceback (most recent call last):\n  File \"/Users/gartung/spack/bin/spack\", line 179, in <module>\n    main()\n  File \"/Users/gartung/spack/bin/spack\", line 157, in main\n    return_val = command(parser, args)\n  File \"/Users/gartung/spack/lib/spack/spack/cmd/graph.py\", line 63, in graph\n    graph_ascii(specs[0], debug=spack.debug)\n  File \"/Users/gartung/spack/lib/spack/spack/graph.py\", line 499, in graph_ascii\n    graph.write(spec, color=color, out=out)\n  File \"/Users/gartung/spack/lib/spack/spack/graph.py\", line 426, in write\n    self._back_edge_line(prev_ends, b, i, False, 'left-1')\n  File \"/Users/gartung/spack/lib/spack/spack/graph.py\", line 303, in _back_edge_line\n    advance(flen,      lambda: [(\"| \", self._pos)] )\n  File \"/Users/gartung/spack/lib/spack/spack/graph.py\", line 280, in advance\n    self._write_edge(*e)\n  File \"/Users/gartung/spack/lib/spack/spack/graph.py\", line 161, in _write_edge\n    name = self._frontier[index][sub]\nIndexError: list index out of range\n",
    "user": "gartung",
    "url": "https://api.github.com/repos/spack/spack/issues/1098",
    "updated_at": "2016-09-28 09:52:48",
    "created_at": "2016-06-22 18:02:27",
    "closed_at": "2016-09-28 04:10:14",
    "state": "closed",
    "title": "spack graph --concretize crashes for complex graphs",
    "number": 1098,
    "milestone": null,
    "labels": [
        "bug",
        "graph"
    ],
    "id": 161747706,
    "html_url": "https://github.com/spack/spack/issues/1098",
    "assignees": [],
    "comments": 6
}