{
    "body": "### Steps to reproduce the issue\r\nHave a spack.yaml + .gitlab-ci.yml file like https://gitlab.com/cscs-ci/ci-testing/spack-ci/-/tree/839a2aa3794865671060c8431175f01bae8ba4b8.\r\n\r\n- This builds `hpx`. \r\n- `hpx` has down the line a dependency on Python\r\n- I believe this confuses spack in the `spack rebuild` step, making it fail to locate the `botocore` module and error next as follows\r\n\r\nTo isolate the problem further, please check out [this minimal setup](https://gitlab.com/cscs-ci/ci-testing/spack-ci/-/blob/84cbc5a7c0821d4d0f8d9cdb66f0a3a6e6128c98/.gitlab-ci.yml) with just the failing job, and check out the pipeline logs: https://cscs-ci.gitlab.io/-/ci-testing/spack-ci/-/jobs/630250913/artifacts/jobs_scratch_dir/logs/pipeline_log.txt.\r\n\r\n### Error Message\r\n\r\n```\r\n==> [2020-07-09-03:55:46.206507, 568] Error: ModuleNotFoundError: No module named 'botocore'\r\n\r\n/opt/spack/lib/spack/spack/package.py:1149, in do_fetch:\r\n       1146                raise FetchError(\"Will not fetch %s\" %\r\n       1147                                 self.spec.format('{name}{@version}'), ck_msg)\r\n       1148\r\n  >>   1149        self.stage.create()\r\n       1150        self.stage.fetch(mirror_only)\r\n       1151        self._fetch_time = time.time() - start_time\r\n       1152\r\n\r\n\r\nTraceback (most recent call last):\r\n  File \"/opt/spack/lib/spack/spack/build_environment.py\", line 838, in child_process\r\n    return_value = function()\r\n  File \"/opt/spack/lib/spack/spack/installer.py\", line 1073, in build_process\r\n    pkg.do_patch()\r\n  File \"/opt/spack/lib/spack/spack/package.py\", line 1189, in do_patch\r\n    self.do_stage()\r\n  File \"/opt/spack/lib/spack/spack/package.py\", line 1174, in do_stage\r\n    self.do_fetch(mirror_only)\r\n  File \"/opt/spack/lib/spack/spack/package.py\", line 1150, in do_fetch\r\n    self.stage.fetch(mirror_only)\r\n  File \"/opt/spack/lib/spack/spack/util/pattern.py\", line 68, in getter\r\n    getattr(item, self.name)(*args, **kwargs)\r\n  File \"/opt/spack/lib/spack/spack/stage.py\", line 464, in fetch\r\n    self.fetcher.fetch()\r\n  File \"/opt/spack/lib/spack/spack/fetch_strategy.py\", line 72, in wrapper\r\n    return fun(self, *args, **kwargs)\r\n  File \"/opt/spack/lib/spack/spack/fetch_strategy.py\", line 1146, in fetch\r\n    _, headers, stream = web_util.read_from_url(self.url)\r\n  File \"/opt/spack/lib/spack/spack/util/web.py\", line 128, in read_from_url\r\n    response = _urlopen(req, timeout=_timeout, context=context)\r\n  File \"/opt/spack/lib/spack/spack/util/web.py\", line 476, in _urlopen\r\n    return opener(req, *args, **kwargs)\r\n  File \"/scratch/snx3000/jenkssl/gitlab-runner-daint/builds/txUXd4Wq/0/cscs-ci-ci-testing-spack-ci/cscs-ci/ci-testing/spack-ci/.spack-env/view/lib/python3.7/urllib/request.py\", line 525, in open\r\n    response = self._open(req, data)\r\n  File \"/scratch/snx3000/jenkssl/gitlab-runner-daint/builds/txUXd4Wq/0/cscs-ci-ci-testing-spack-ci/cscs-ci/ci-testing/spack-ci/.spack-env/view/lib/python3.7/urllib/request.py\", line 543, in _open\r\n    '_open', req)\r\n  File \"/scratch/snx3000/jenkssl/gitlab-runner-daint/builds/txUXd4Wq/0/cscs-ci-ci-testing-spack-ci/cscs-ci/ci-testing/spack-ci/.spack-env/view/lib/python3.7/urllib/request.py\", line 503, in _call_chain\r\n    result = func(*args)\r\n  File \"/opt/spack/lib/spack/spack/s3_handler.py\", line 64, in s3_open\r\n    from botocore.exceptions import ClientError\r\nModuleNotFoundError: No module named 'botocore'\r\n```\r\n\r\nNote the paths to `spack-ci/.spack-env/view/lib/python3.7/urllib/request.py`, it's probably using the wrong python version.\r\n\r\n### Information on your system\r\n\r\nI can't really provide this, it's running in CI.\r\n\r\n### Additional information\r\n\r\n- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform\r\n- [x] I have searched the issues of this repo and believe this is not a duplicate\r\n- [x] I have run the failing commands in debug mode and reported the output\r\n\r\n",
    "user": "haampie",
    "url": "https://api.github.com/repos/spack/spack/issues/17432",
    "updated_at": "2020-07-09 10:31:03",
    "created_at": "2020-07-09 02:10:27",
    "closed_at": "None",
    "state": "open",
    "title": "spack rebuild seems to use wrong python version when it is in the environment",
    "number": 17432,
    "milestone": null,
    "labels": [
        "bug",
        "triage"
    ],
    "id": 653707811,
    "html_url": "https://github.com/spack/spack/issues/17432",
    "assignees": [],
    "comments": 1
}